### ISSUE TITLE
a fatal error

### ISSUE THREAD

**Issue by svtary** [MAPIRlab/Gas-Source-Localization#1]
hi, when i run catkin_make , there is an error called:catkin_ws/src/Gas-Source-Localization/gsl_actionserver/include/gsl_grid.h:11:46: fatal error: gmrf_wind_mapping/WindEstimation.h:  no such 
file or directory .
i run catkin_make twice ,it doesn't work.so i use CATKIN_IGNORE ,also failed.
i realize the olfaction_msgs package has no WindEstimation ,so i do not know how to deal with this error.i am  a beginner in this field ,could u help me?thank you very much!!!

**Comment by PepeOjeda** [comment]
Hello.
I'm sorry for the delayed answer, I was not receiving notifications for this repository. The problem can be fixed by installing the following package: https://github.com/MAPIRlab/GMRF-wind

If you do not plan on using the infotaxis version of the grid algorithm, you might also be able to solve it by simply deleting any references to the windEstimation in the code, as the rest of the algorithms do not depend on it. However, I do recommend just installing it, as it will be easier.
