### ISSUE TITLE
gmrf_wind_mapping/WindEstimation.h: No such file or directory

### ISSUE THREAD

**Issue by kurosh-z** [MAPIRlab/Gas-Source-Localization#4]
Hi, 
 I installed gmrf_wind_mapping but it seems to have no header file WindEstimation.h. 

![gmrf](https://user-images.githubusercontent.com/32224317/204784385-2c73b19e-389c-477c-82ba-9a4436a5bda8.png)

**Comment by PepeOjeda** [comment]
Hello. 

WindEstimation is a ROS message (a service, really), so the header gets auto-generated from the .srv file when you run catkin_make. 
The error you are getting usually gets fixed by simply running the compilation command again, since the message header will already have been generated the first time. If that somehow doesn't fix it, try compiling the gmrf package on its own first.

I'll try to fix this the "proper" way (with build dependencies) at some point, but that workaround should be easy enough for now.
